[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
]
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"

[licenses]
version = 2
private = { ignore = true }
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
]
confidence-threshold = 0.9
exceptions = [
    { name = "unicode-ident", allow = [
        "Unicode-DFS-2016",
    ] },
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC AND BSD-3-Clause"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
    { path = "third-party/chromium/LICENSE", hash = 0x001c7e6c },
]

[bans]
multiple-versions = "deny"
# Lint level for when a crate version requirement is `*`
wildcards = "deny"
highlight = "simplest-path"
workspace-default-features = "allow"
external-default-features = "allow"
allow-wildcard-paths = true


skip = [
    { name = "socket2", version = "0.4.10", reason = "zbus v3" },
    { name = "syn", version = "1.0.109", reason = "zbus v3" },
    { name = "rustix", version = "0.37.27", reason = "zbus v3" },
    { name = "polling", version = "2.8.0", reason = "zbus v3" },
    { name = "linux-raw-sys", version = "0.3.8", reason = "zbus v3" },
    { name = "futures-lite", version = "1.13.0", reason = "zbus v3" },
    { name = "event-listener", version = "2.5.3", reason = "zbus v3" },
    { name = "event-listener", version = "3.1.0", reason = "zbus v3" },
    { name = "async-io", version = "1.13.0", reason = "zbus v3" },
    { name = "async-lock", version = "2.8.0", reason = "zbus v3" },
    { name = "bitflags", version = "1.3.2", reason = "zbus v3" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/nikarh/secret-service-rs"]
